# Generated by Django 5.2.7 on 2025-11-01 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_date_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
